### ISSUE TITLE
Provision development MongoDB server with docker-compose

### ISSUE THREAD

**Issue by aeksco** [rcos/Observatory3#668]
Rather than developers installing MongoDB and running `mongod` in a separate shell, perhaps it would be easier to bundle a `docker-compose.yml` file in the repository to provision Observatory's requisite development infrastructure. I'm more than happy to take on this task - @agundy thoughts?

**Comment by aeksco** [comment]
Just tested this on my local machine - works very nicely:

```yml
version: "3"

services:

  mongodb:
    image: mongo
    container_name: observatory_mongo
    ports:
      - "27017:27017"

  mongo_admin:
    image: mongo-express
    container_name: observatory_mongo_admin
    links:
      - mongodb:mongo
    ports:
      - "8081:8081"
```

This `docker-compose.yml` file includes MongoDB, as well as a container running [mongo-express](https://github.com/mongo-express/mongo-express) - a nice admin interface for MongoDB written in Node/Express.

![screenshot from 2017-10-05 16-12-43](https://user-images.githubusercontent.com/4616233/31250365-934a7edc-a9e8-11e7-80a3-140de6238d08.png)

I can open up a PR if this is something we want in our development environment.
